spring.application.name=finance-api

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# Displays SQL queries in the console (great for debugging and study)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Since you have already created the tables in Postgres, we set ddl-auto to 'validate' or 'none'.
# so that Spring does not attempt to automatically recreate or alter your tables.
spring.jpa.hibernate.ddl-auto=validate
